server:
  port: 8081
spring:
  application:
    name: age_server
  profiles:
    active: chaos-monkey
  datasource:
    url: jdbc:h2:mem:age_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, chaosmonkey
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: false
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true

