server:
  port: 8080
spring:
  application:
    name: backend-web-app
  profiles:
    active: chaos-monkey
  datasource:
    url: jdbc:h2:mem:age_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
management:
  endpoints:
    web:
      exposure:
        include: health, info, chaosmonkey, prometheus
  endpoint:
    metrics:
      enabled: true
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
      percentiles-histogram[http.server.requests]: true
      sla:
        http.server.requests: 100ms, 200ms
chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: true
      repository: true
      rest-controller: true
      service: true
    assaults:
      latency-active: true
      latency-range-start: 200
      latency-range-end: 2000
